// Generated by F1 (pdlc-merge-phase) — byte-identity goldens.
//
// Captured from `updateQueueStatus` in orchestrate-queue.js at HEAD, BEFORE
// B2 changes its signature to accept an `evidence` parameter (PLAN §5, F1 ->
// B1 -> B2 ordering; TSPEC §13.5; PROPERTIES §5 PROP-M-12).
//
// goldens[shapeName][status] === updateQueueStatus(QUEUE_SHAPES[shapeName], FEATURE, status)
// evaluated against the pre-change 3-parameter function. Consumed by
// mergeQueueWriteback.test.js (B2) as the third, non-circular arm of
// PROP-M-12's three-way equality (TE F-11). These are frozen values, not a
// re-derivation -- do not regenerate them from a modified updateQueueStatus.

import { QUEUE_SHAPES, FEATURE } from "./shapes.js";

export const QUEUE_GOLDENS = {
  "canonical5col": {
    "pending": {
      "markdown": "| Order | Status | Feature | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | pending | demo-feature | docs/demo-feature/REQ-demo-feature.md | - |\n| 2 | pending | other-feature-a | docs/other-feature-a/REQ-other-feature-a.md | - |\n| 3 | done | other-feature-b | docs/other-feature-b/REQ-other-feature-b.md | demo-feature |",
      "matched": true
    },
    "in-progress": {
      "markdown": "| Order | Status | Feature | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | in-progress | demo-feature | docs/demo-feature/REQ-demo-feature.md | - |\n| 2 | pending | other-feature-a | docs/other-feature-a/REQ-other-feature-a.md | - |\n| 3 | done | other-feature-b | docs/other-feature-b/REQ-other-feature-b.md | demo-feature |",
      "matched": true
    },
    "awaiting-merge": {
      "markdown": "| Order | Status | Feature | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | awaiting-merge | demo-feature | docs/demo-feature/REQ-demo-feature.md | - |\n| 2 | pending | other-feature-a | docs/other-feature-a/REQ-other-feature-a.md | - |\n| 3 | done | other-feature-b | docs/other-feature-b/REQ-other-feature-b.md | demo-feature |",
      "matched": true
    },
    "done": {
      "markdown": "| Order | Status | Feature | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | done | demo-feature | docs/demo-feature/REQ-demo-feature.md | - |\n| 2 | pending | other-feature-a | docs/other-feature-a/REQ-other-feature-a.md | - |\n| 3 | done | other-feature-b | docs/other-feature-b/REQ-other-feature-b.md | demo-feature |",
      "matched": true
    },
    "blocked": {
      "markdown": "| Order | Status | Feature | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | blocked | demo-feature | docs/demo-feature/REQ-demo-feature.md | - |\n| 2 | pending | other-feature-a | docs/other-feature-a/REQ-other-feature-a.md | - |\n| 3 | done | other-feature-b | docs/other-feature-b/REQ-other-feature-b.md | demo-feature |",
      "matched": true
    },
    "halted": {
      "markdown": "| Order | Status | Feature | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | halted | demo-feature | docs/demo-feature/REQ-demo-feature.md | - |\n| 2 | pending | other-feature-a | docs/other-feature-a/REQ-other-feature-a.md | - |\n| 3 | done | other-feature-b | docs/other-feature-b/REQ-other-feature-b.md | demo-feature |",
      "matched": true
    }
  },
  "alreadyMigrated": {
    "pending": {
      "markdown": "| Order | Status | Feature | REQ Path | Depends-On | Evidence |\n| --- | --- | --- | --- | --- | --- |\n| 1 | pending | demo-feature | docs/demo-feature/REQ-demo-feature.md | - | - |\n| 2 | done | other-feature-a | docs/other-feature-a/REQ-other-feature-a.md | - | abc1234 #9 |",
      "matched": true
    },
    "in-progress": {
      "markdown": "| Order | Status | Feature | REQ Path | Depends-On | Evidence |\n| --- | --- | --- | --- | --- | --- |\n| 1 | in-progress | demo-feature | docs/demo-feature/REQ-demo-feature.md | - | - |\n| 2 | done | other-feature-a | docs/other-feature-a/REQ-other-feature-a.md | - | abc1234 #9 |",
      "matched": true
    },
    "awaiting-merge": {
      "markdown": "| Order | Status | Feature | REQ Path | Depends-On | Evidence |\n| --- | --- | --- | --- | --- | --- |\n| 1 | awaiting-merge | demo-feature | docs/demo-feature/REQ-demo-feature.md | - | - |\n| 2 | done | other-feature-a | docs/other-feature-a/REQ-other-feature-a.md | - | abc1234 #9 |",
      "matched": true
    },
    "done": {
      "markdown": "| Order | Status | Feature | REQ Path | Depends-On | Evidence |\n| --- | --- | --- | --- | --- | --- |\n| 1 | done | demo-feature | docs/demo-feature/REQ-demo-feature.md | - | - |\n| 2 | done | other-feature-a | docs/other-feature-a/REQ-other-feature-a.md | - | abc1234 #9 |",
      "matched": true
    },
    "blocked": {
      "markdown": "| Order | Status | Feature | REQ Path | Depends-On | Evidence |\n| --- | --- | --- | --- | --- | --- |\n| 1 | blocked | demo-feature | docs/demo-feature/REQ-demo-feature.md | - | - |\n| 2 | done | other-feature-a | docs/other-feature-a/REQ-other-feature-a.md | - | abc1234 #9 |",
      "matched": true
    },
    "halted": {
      "markdown": "| Order | Status | Feature | REQ Path | Depends-On | Evidence |\n| --- | --- | --- | --- | --- | --- |\n| 1 | halted | demo-feature | docs/demo-feature/REQ-demo-feature.md | - | - |\n| 2 | done | other-feature-a | docs/other-feature-a/REQ-other-feature-a.md | - | abc1234 #9 |",
      "matched": true
    }
  },
  "paddedCells": {
    "pending": {
      "markdown": "| Order | Status       | Feature        | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | pending | demo-feature | docs/demo-feature/REQ-demo-feature.md | - |",
      "matched": true
    },
    "in-progress": {
      "markdown": "| Order | Status       | Feature        | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | in-progress | demo-feature | docs/demo-feature/REQ-demo-feature.md | - |",
      "matched": true
    },
    "awaiting-merge": {
      "markdown": "| Order | Status       | Feature        | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | awaiting-merge | demo-feature | docs/demo-feature/REQ-demo-feature.md | - |",
      "matched": true
    },
    "done": {
      "markdown": "| Order | Status       | Feature        | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | done | demo-feature | docs/demo-feature/REQ-demo-feature.md | - |",
      "matched": true
    },
    "blocked": {
      "markdown": "| Order | Status       | Feature        | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | blocked | demo-feature | docs/demo-feature/REQ-demo-feature.md | - |",
      "matched": true
    },
    "halted": {
      "markdown": "| Order | Status       | Feature        | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | halted | demo-feature | docs/demo-feature/REQ-demo-feature.md | - |",
      "matched": true
    }
  },
  "oneDataRow": {
    "pending": {
      "markdown": "| Order | Status | Feature | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | pending | demo-feature | docs/demo-feature/REQ-demo-feature.md | - |",
      "matched": true
    },
    "in-progress": {
      "markdown": "| Order | Status | Feature | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | in-progress | demo-feature | docs/demo-feature/REQ-demo-feature.md | - |",
      "matched": true
    },
    "awaiting-merge": {
      "markdown": "| Order | Status | Feature | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | awaiting-merge | demo-feature | docs/demo-feature/REQ-demo-feature.md | - |",
      "matched": true
    },
    "done": {
      "markdown": "| Order | Status | Feature | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | done | demo-feature | docs/demo-feature/REQ-demo-feature.md | - |",
      "matched": true
    },
    "blocked": {
      "markdown": "| Order | Status | Feature | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | blocked | demo-feature | docs/demo-feature/REQ-demo-feature.md | - |",
      "matched": true
    },
    "halted": {
      "markdown": "| Order | Status | Feature | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | halted | demo-feature | docs/demo-feature/REQ-demo-feature.md | - |",
      "matched": true
    }
  },
  "featureAbsent": {
    "pending": {
      "markdown": "| Order | Status | Feature | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | pending | other-feature-a | docs/other-feature-a/REQ-other-feature-a.md | - |\n| 2 | done | other-feature-b | docs/other-feature-b/REQ-other-feature-b.md | - |",
      "matched": false
    },
    "in-progress": {
      "markdown": "| Order | Status | Feature | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | pending | other-feature-a | docs/other-feature-a/REQ-other-feature-a.md | - |\n| 2 | done | other-feature-b | docs/other-feature-b/REQ-other-feature-b.md | - |",
      "matched": false
    },
    "awaiting-merge": {
      "markdown": "| Order | Status | Feature | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | pending | other-feature-a | docs/other-feature-a/REQ-other-feature-a.md | - |\n| 2 | done | other-feature-b | docs/other-feature-b/REQ-other-feature-b.md | - |",
      "matched": false
    },
    "done": {
      "markdown": "| Order | Status | Feature | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | pending | other-feature-a | docs/other-feature-a/REQ-other-feature-a.md | - |\n| 2 | done | other-feature-b | docs/other-feature-b/REQ-other-feature-b.md | - |",
      "matched": false
    },
    "blocked": {
      "markdown": "| Order | Status | Feature | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | pending | other-feature-a | docs/other-feature-a/REQ-other-feature-a.md | - |\n| 2 | done | other-feature-b | docs/other-feature-b/REQ-other-feature-b.md | - |",
      "matched": false
    },
    "halted": {
      "markdown": "| Order | Status | Feature | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | pending | other-feature-a | docs/other-feature-a/REQ-other-feature-a.md | - |\n| 2 | done | other-feature-b | docs/other-feature-b/REQ-other-feature-b.md | - |",
      "matched": false
    }
  },
  "noTable": {
    "pending": {
      "markdown": "# Queue\n\nThere is no table here at all — just prose describing the queue informally.\ndemo-feature is mentioned but not in tabular form.",
      "matched": false
    },
    "in-progress": {
      "markdown": "# Queue\n\nThere is no table here at all — just prose describing the queue informally.\ndemo-feature is mentioned but not in tabular form.",
      "matched": false
    },
    "awaiting-merge": {
      "markdown": "# Queue\n\nThere is no table here at all — just prose describing the queue informally.\ndemo-feature is mentioned but not in tabular form.",
      "matched": false
    },
    "done": {
      "markdown": "# Queue\n\nThere is no table here at all — just prose describing the queue informally.\ndemo-feature is mentioned but not in tabular form.",
      "matched": false
    },
    "blocked": {
      "markdown": "# Queue\n\nThere is no table here at all — just prose describing the queue informally.\ndemo-feature is mentioned but not in tabular form.",
      "matched": false
    },
    "halted": {
      "markdown": "# Queue\n\nThere is no table here at all — just prose describing the queue informally.\ndemo-feature is mentioned but not in tabular form.",
      "matched": false
    }
  }
};

export { QUEUE_SHAPES, FEATURE };
