// Generated by F1 (pdlc-merge-phase) — captured queue-shape fixtures.
// DO NOT hand-edit the string literals below without re-deriving the goldens
// in ./index.js from the CURRENT updateQueueStatus at the same time.
//
// One markdown string per queue shape named in PROPERTIES §5 PROP-M-12's
// domain: 5-column canonical, already-migrated (Evidence column present),
// padded cells, one data row, feature absent, no table at all.

export const FEATURE = "demo-feature";

export const QUEUE_SHAPES = {
  "canonical5col": "| Order | Status | Feature | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | pending | demo-feature | docs/demo-feature/REQ-demo-feature.md | - |\n| 2 | pending | other-feature-a | docs/other-feature-a/REQ-other-feature-a.md | - |\n| 3 | done | other-feature-b | docs/other-feature-b/REQ-other-feature-b.md | demo-feature |",
  "alreadyMigrated": "| Order | Status | Feature | REQ Path | Depends-On | Evidence |\n| --- | --- | --- | --- | --- | --- |\n| 1 | pending | demo-feature | docs/demo-feature/REQ-demo-feature.md | - | - |\n| 2 | done | other-feature-a | docs/other-feature-a/REQ-other-feature-a.md | - | abc1234 #9 |",
  "paddedCells": "| Order | Status       | Feature        | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1   |  pending   |  demo-feature   | docs/demo-feature/REQ-demo-feature.md | - |",
  "oneDataRow": "| Order | Status | Feature | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | pending | demo-feature | docs/demo-feature/REQ-demo-feature.md | - |",
  "featureAbsent": "| Order | Status | Feature | REQ Path | Depends-On |\n| --- | --- | --- | --- | --- |\n| 1 | pending | other-feature-a | docs/other-feature-a/REQ-other-feature-a.md | - |\n| 2 | done | other-feature-b | docs/other-feature-b/REQ-other-feature-b.md | - |",
  "noTable": "# Queue\n\nThere is no table here at all — just prose describing the queue informally.\ndemo-feature is mentioned but not in tabular form."
};
