// Prompt-composition coverage over the FULL dispatchable set (T24, red).
//
// PROPERTIES-pdlc-headless-engine.md: PROP-SKILL-7, 8, 10, 11, 12, 13, 15
// FSPEC §6.4/§6.5/§6.6: AT-ENG-20, AT-ENG-21, AT-ENG-23, AT-ENG-24, AT-ENG-25
//
// This file is deliberately red at HEAD: `composeDispatchPrompt` only inlines
// ONE file (skills.mjs:312) and `_agent` reads one skill per dispatch with no
// notion of a supplement set (adapter.mjs:308-319). T38 implements the
// whole-prompt-file-set inlining this file specifies; until then several
// cases below are expected to fail.
//
// "One invocation per member, never a sample" (BR-SKILL-6) is honoured at the
// TEST level too: the sweep below generates one `test()` per member of the
// dispatchable set via a loop, rather than one test asserting over an array,
// so a single missing member fails its own named test instead of hiding
// inside an aggregate.

import { test } from "node:test";
import assert from "node:assert/strict";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { readFileSync, readdirSync } from "node:fs";

import { loadSkill, composeDispatchPrompt } from "../lib/skills.mjs";
import { createAdapter } from "../lib/adapter.mjs";
import { DISPATCHABLE_SKILLS as DEV_SKILLS } from "../../workflows/orchestrate-dev.js";
import { DISPATCHABLE_SKILLS as QUEUE_SKILLS } from "../../workflows/orchestrate-queue.js";

const engineRoot = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const repoRoot = path.dirname(path.dirname(engineRoot));
const PLUGIN_ROOT = path.join(repoRoot, "pdlc");

// ── the dispatchable set, TSPEC §4.4 / FSPEC §6.4 ──────────────────────────────
//
// "the identifiers the modules can dispatch, plus the two supplements" — the
// union of both modules' exported DISPATCHABLE_SKILLS, plus se-implement's two
// language supplements (the only identifier with more than one prompt file).
export const DISPATCHABLE_SET = Object.freeze(
  [...new Set([...DEV_SKILLS, ...QUEUE_SKILLS])].sort()
);

const SE_IMPLEMENT_SUPPLEMENTS = Object.freeze([
  "se-implement:SKILL-typescript.md",
  "se-implement:SKILL-python.md",
]);

// The transcribed 10 (TE F-42 / BR-START-4's test-side-only transcription):
// this is deliberately NOT imported from anywhere — a change here must be a
// human decision, same reasoning as EXPECTED_SKILLS and the workflows-side
// derivation test.
const EXPECTED_DISPATCHABLE_SET = [
  "dod-verify",
  "harvest-learnings",
  "pm-author",
  "pm-review",
  "se-author",
  "se-implement",
  "se-review",
  "ship-pr",
  "te-author",
  "te-review",
].sort();

test("DISPATCHABLE_SET (union of both modules) is exactly the transcribed 10", () => {
  assert.deepEqual(DISPATCHABLE_SET, EXPECTED_DISPATCHABLE_SET);
});

/** Every `.md` file directly under a skill's plugin directory, sorted, SKILL.md first. */
function promptFileSet(identifier) {
  const dir = path.join(PLUGIN_ROOT, "skills", identifier);
  const names = readdirSync(dir).filter((f) => f.endsWith(".md"));
  names.sort((a, b) => (a === "SKILL.md" ? -1 : b === "SKILL.md" ? 1 : a.localeCompare(b)));
  return names;
}

// ── PROP-SKILL-7 / AT-ENG-20 — every member, one invocation, full text ────────
//
// "one invocation per member, never a sample" (BR-SKILL-6): a real `test()`
// per identifier, generated by a loop rather than asserted inside one.

for (const identifier of DISPATCHABLE_SET) {
  test(`composed prompt for "${identifier}" contains that skill's full prompt-file set — AT-ENG-20`, () => {
    const files = promptFileSet(identifier);
    const loaded = loadSkill(PLUGIN_ROOT, identifier);
    // Every dispatch must carry SKILL.md verbatim, whatever else it carries.
    const skillMdPath = path.join(PLUGIN_ROOT, "skills", identifier, "SKILL.md");
    const skillMdText = readFileSync(skillMdPath, "utf8");
    const composed = composeDispatchPrompt(identifier, loaded.text, "Do the task.");
    assert.ok(
      composed.includes(skillMdText),
      `composed prompt for "${identifier}" must inline SKILL.md verbatim`
    );

    // PROP-SKILL-8 / AT-ENG-23: identifiers with supplements (only
    // se-implement, at HEAD) must carry every supplement's full text too —
    // this is the part that is red until T38 teaches composition about the
    // whole directory, not just the one file `loadSkill` was asked for.
    const supplements = files.filter((f) => f !== "SKILL.md");
    for (const supplement of supplements) {
      const supplementText = readFileSync(
        path.join(PLUGIN_ROOT, "skills", identifier, supplement),
        "utf8"
      );
      assert.ok(
        composed.includes(supplementText),
        `composed prompt for "${identifier}" must also inline supplement "${supplement}" ` +
          `(BR-SKILL-3, PROP-SKILL-8) — not carried by a single-file composeDispatchPrompt call`
      );
    }
  });
}

// ── PROP-SKILL-8 / AT-ENG-23 — delimiter grammar, SET-EQUALITY not containment ─
//
// TSPEC §3.3: "AC-3.1's oracle is set-equality over the file set, not
// containment of a supplement's text somewhere in the prompt: for each
// dispatched identifier, the set of basenames appearing in BEGIN markers ≡
// the set of .md files in that identifier's skill directory." Containment
// would pass a prompt that inlined a supplement twice, or one that inlined a
// file no longer in the directory — this asserts the stronger claim.
//
// The delimiter is fixed: `--- BEGIN SUPPLEMENT: {basename} ---` /
// `--- END SUPPLEMENT: {basename} ---`.

function supplementBasenamesInPrompt(composed) {
  const re = /--- BEGIN SUPPLEMENT: (.+?) ---/g;
  const out = [];
  let m;
  while ((m = re.exec(composed))) out.push(m[1]);
  return out.sort();
}

test("se-implement: supplement basenames in the composed prompt are exactly the directory's non-SKILL.md files — PROP-SKILL-8", () => {
  const files = promptFileSet("se-implement");
  const expectedSupplements = files.filter((f) => f !== "SKILL.md").sort();
  assert.deepEqual(expectedSupplements, ["SKILL-python.md", "SKILL-typescript.md"]);

  const loaded = loadSkill(PLUGIN_ROOT, "se-implement");
  const composed = composeDispatchPrompt("se-implement", loaded.text, "Implement task A1.");
  assert.deepEqual(
    supplementBasenamesInPrompt(composed),
    expectedSupplements,
    "composeDispatchPrompt does not yet emit BEGIN/END SUPPLEMENT markers at all (T38)"
  );
});

test("a plain skill with no supplements (e.g. pm-author) emits zero SUPPLEMENT markers", () => {
  const loaded = loadSkill(PLUGIN_ROOT, "pm-author");
  const composed = composeDispatchPrompt("pm-author", loaded.text, "Write REQ.");
  assert.deepEqual(supplementBasenamesInPrompt(composed), []);
});

// ── PROP-SKILL-15 / AT-ENG-21 — provenance, not substring absence ─────────────
//
// "the prompt must equal the concatenation of the identifier's prompt-file
// set (PROP-SKILL-7/8) plus the module-supplied dispatch text, with no
// engine-authored segment between them". Stated positively: strip every
// prompt-file's own bytes and the task text out of the composed string, and
// what remains (the engine's own scaffolding) must contain neither a
// Skill-tool instruction nor an engine-added `pdlc:` reference.
//
// This is asserted over EVERY member of the dispatchable set, on ONE
// dry-run-shaped composition per member — the same sweep PROP-SKILL-7 uses —
// so the two halves of AC-3.1 read as one composition (TSPEC).
for (const identifier of DISPATCHABLE_SET) {
  test(`no engine-authored segment in the "${identifier}" composition names Skill tool or pdlc: — AT-ENG-21`, () => {
    const files = promptFileSet(identifier);
    const loaded = loadSkill(PLUGIN_ROOT, identifier);
    const taskText = `[dry run] no task dispatched for ${identifier}.`;
    const composed = composeDispatchPrompt(identifier, loaded.text, taskText);

    let scaffolding = composed;
    for (const file of files) {
      const text = readFileSync(path.join(PLUGIN_ROOT, "skills", identifier, file), "utf8");
      scaffolding = scaffolding.split(text).join("");
    }
    scaffolding = scaffolding.split(taskText).join("");

    assert.equal(
      /Skill tool/i.test(scaffolding),
      false,
      `engine scaffolding for "${identifier}" must not instruct a Skill-tool call:\n${scaffolding}`
    );
    assert.equal(
      /pdlc:/.test(scaffolding),
      false,
      `engine scaffolding for "${identifier}" must not add a pdlc: namespace reference:\n${scaffolding}`
    );
  });
}

// EC-SKILL-5 (permitted case, FSPEC:635): a prompt file whose own PROSE
// contains "pdlc:" must dispatch unchanged and must not be flagged — BR-SKILL-1
// constrains what the ENGINE adds, never what a skill author wrote.
test("EC-SKILL-5: a skill file whose own prose contains pdlc: dispatches unchanged, unflagged", () => {
  const skillText =
    "# scratch-skill\n\nSee the /pdlc:pm-author skill for background. This prose is the skill author's.";
  const composed = composeDispatchPrompt("scratch-skill", skillText, "Do the thing.");
  assert.ok(composed.includes(skillText), "the skill's own prose must survive verbatim");
  assert.ok(composed.includes("/pdlc:pm-author"), "the engine must not strip the skill author's own pdlc: reference");
});

// The falsifier: prove the oracle used above actually fires on a corrupted
// composition, so a green suite is not vacuously green (consolidation-agent
// lesson). This exercises the SAME stripping logic the sweep above uses,
// against a scratch string the "engine" was made to corrupt.
test("the AT-ENG-21 oracle fires: a prepended Skill-tool line fails the property", () => {
  const skillText = "# pm-author\n\nAuthor the REQ.";
  const taskText = "Write the REQ.";
  const clean = composeDispatchPrompt("pm-author", skillText, taskText);
  const corrupted = `Use the Skill tool to invoke pdlc:pm-author first.\n\n${clean}`;

  function scaffoldingOf(composed) {
    return composed.split(skillText).join("").split(taskText).join("");
  }

  assert.equal(/Skill tool/i.test(scaffoldingOf(clean)), false, "the clean composition must pass");
  assert.equal(
    /Skill tool/i.test(scaffoldingOf(corrupted)),
    true,
    "a corrupted composition with an injected Skill-tool line must fail the property"
  );
});

// ── PROP-SKILL-10 / AT-ENG-24 — dry-run inertness is asserted, not assumed ────
//
// BR-SKILL-5: on the dry-run path an attempted dispatch is a failure the
// surface reports, not a silently-executed call. The CLI wires this via
// `inertTransport()` (bin/pdlc.mjs:97-104) — a transport whose `dispatch()`
// throws. This exercises the same shape directly against the adapter: an
// attempted `_agent()` call over an inert transport must reject (propagate
// the failure), never resolve with agent output.

function inertTransport() {
  return {
    dispatch() {
      throw new Error("dry run: dispatch attempted — the dry-run surface must not contact a model");
    },
  };
}

test("an attempted dispatch over the dry-run (inert) transport fails the call, never silently succeeds", async () => {
  const adapter = createAdapter({
    transport: inertTransport(),
    pluginRoot: PLUGIN_ROOT,
    log: () => {},
  });
  await assert.rejects(
    () => adapter._agent("pm-author", "Write REQ."),
    /dispatch attempted/,
    "an attempted dispatch on the dry-run path must be reported as a failure of the run"
  );
});

test("composePrompt (the dry-run surface itself) never touches the transport", () => {
  const transport = inertTransport();
  const adapter = createAdapter({ transport, pluginRoot: PLUGIN_ROOT, log: () => {} });
  // Must not throw: composing a prompt is not dispatching one.
  const composed = adapter.composePrompt("pm-author", "[dry run] no task dispatched.");
  assert.match(composed, /BEGIN ROLE DEFINITION: pm-author/);
});

// ── PROP-SKILL-11 / AT-ENG-25 — EC-SKILL-1, EC-SKILL-2, EC-RUN-1 ──────────────
//
// "A prompt file deleted or emptied between startup and a later dispatch must
// fail that dispatch as a transport-independent engine error naming the
// identifier and path — an empty role must never be dispatched." Three
// triggers, one case each, since prompt bytes are read per dispatch
// (BR-SKILL-4): the file emptied, the file deleted, and the whole plugin tree
// removed while the run is in flight (EC-RUN-1) — a different trigger from
// the first two, its own fixture.

/** A fake fs whose readFileSync/existsSync can be told to fail after N calls. */
function flakyFs(initial, { failAfter = null, failWith = null } = {}) {
  let calls = 0;
  return {
    existsSync: (p) => Object.hasOwn(initial, p),
    readFileSync: (p) => {
      calls += 1;
      if (failAfter != null && calls > failAfter) {
        const err = new Error(failWith || `ENOENT: no such file or directory, open '${p}'`);
        err.code = "ENOENT";
        throw err;
      }
      if (!Object.hasOwn(initial, p)) {
        const err = new Error(`ENOENT: no such file or directory, open '${p}'`);
        err.code = "ENOENT";
        throw err;
      }
      return initial[p];
    },
    readdirSync: () => {
      throw new Error("flakyFs: readdirSync not needed by these fixtures");
    },
  };
}

test("EC-SKILL-1: prompt file deleted before dispatch fails naming the identifier and path, never an empty prompt", async () => {
  const file = path.join("/plugin", "skills", "pm-author", "SKILL.md");
  const fs = flakyFs({ [file]: "# pm-author\n\nAuthor the REQ." }, { failAfter: 0 });
  const transport = { calls: [], dispatch: async function (prompt, opts) { this.calls.push({ prompt, opts }); return { text: "x" }; } };
  const adapter = createAdapter({
    transport,
    pluginRoot: "/plugin",
    log: () => {},
    loadSkillFn: (root, name) => loadSkill(root, name, { fs }),
  });
  await assert.rejects(() => adapter._agent("pm-author", "Write REQ."), (err) => {
    assert.match(err.message, /pm-author/);
    assert.match(err.message, /SKILL\.md/);
    return true;
  });
  assert.equal(transport.calls.length, 0, "a deleted prompt file must never reach dispatch, not even with empty text");
});

test("EC-SKILL-2: prompt file present but empty at dispatch time fails the same way as EC-SKILL-1", async () => {
  const file = path.join("/plugin", "skills", "pm-author", "SKILL.md");
  const fs = flakyFs({ [file]: "   \n\n" });
  const transport = { calls: [], dispatch: async function (prompt, opts) { this.calls.push({ prompt, opts }); return { text: "x" }; } };
  const adapter = createAdapter({
    transport,
    pluginRoot: "/plugin",
    log: () => {},
    loadSkillFn: (root, name) => loadSkill(root, name, { fs }),
  });
  await assert.rejects(() => adapter._agent("pm-author", "Write REQ."), /empty file/);
  assert.equal(transport.calls.length, 0, "an empty role must never be dispatched");
});

test("EC-RUN-1: the whole plugin tree removed mid-run is its own fixture, distinct from a single missing file", async () => {
  // Two skills share one adapter/run: the first dispatch succeeds while the
  // tree is intact, then the WHOLE tree (not just one file) goes missing
  // before the second, uncached skill is dispatched.
  const pmAuthor = path.join("/plugin", "skills", "pm-author", "SKILL.md");
  const seAuthor = path.join("/plugin", "skills", "se-author", "SKILL.md");
  let treeRemoved = false;
  const fs = {
    existsSync: (p) => !treeRemoved && (p === pmAuthor || p === seAuthor),
    readFileSync: (p) => {
      if (treeRemoved) {
        const err = new Error(`ENOENT: no such file or directory, open '${p}'`);
        err.code = "ENOENT";
        throw err;
      }
      if (p === pmAuthor) return "# pm-author\n\nAuthor the REQ.";
      if (p === seAuthor) return "# se-author\n\nAuthor the TSPEC.";
      const err = new Error(`ENOENT: ${p}`);
      err.code = "ENOENT";
      throw err;
    },
  };
  const transport = { calls: [], dispatch: async function (prompt, opts) { this.calls.push({ prompt, opts }); return { text: "x" }; } };
  const adapter = createAdapter({
    transport,
    pluginRoot: "/plugin",
    log: () => {},
    loadSkillFn: (root, name) => loadSkill(root, name, { fs }),
  });
  await adapter._agent("pm-author", "Write REQ.");
  assert.equal(transport.calls.length, 1, "the first dispatch, tree intact, must succeed");

  treeRemoved = true; // the whole plugin tree vanishes while the run is in flight
  await assert.rejects(() => adapter._agent("se-author", "Write TSPEC."), (err) => {
    assert.match(err.message, /se-author/);
    return true;
  });
  assert.equal(transport.calls.length, 1, "no dispatch may proceed once the plugin tree is gone");
});

// ── PROP-SKILL-12 / AT-ENG-25 — EC-SKILL-3 ────────────────────────────────────
//
// "A module dispatching an identifier startup did not know about must raise
// an engine error naming the identifier, never a best-effort dispatch with no
// prompt." Against the real plugin tree, an identifier with no directory at
// all demonstrates this: it can never resolve to a prompt file, so the only
// two possible behaviours are "refuse" and "dispatch with no role text" —
// this asserts the former.
test("EC-SKILL-3: an identifier startup did not know about raises, naming the identifier, never a bare dispatch", async () => {
  const transport = { calls: [], dispatch: async function (prompt, opts) { this.calls.push({ prompt, opts }); return { text: "x" }; } };
  const adapter = createAdapter({ transport, pluginRoot: PLUGIN_ROOT, log: () => {} });
  await assert.rejects(() => adapter._agent("not-a-real-skill", "do something"), /not-a-real-skill/);
  assert.equal(transport.calls.length, 0, "never a best-effort dispatch with no prompt");
});

// ── PROP-SKILL-13 / AT-ENG-25 — EC-SKILL-4, integration ───────────────────────
//
// "A plugin upgraded mid-run must not change the run: it continues against
// the version the handshake approved, and a version change is discovered by
// the next run's handshake." `pluginRoot` is resolved once, at startup, and
// closed over by the adapter for its whole lifetime (adapter.mjs: `pluginRoot`
// constructor arg, never re-resolved by `_agent`/`skillTextFor`) — this proves
// that structurally: a fake fs that would resolve a NEWER version if asked
// again never gets asked again, so every dispatch across the run keeps
// reading the handshake-approved root.
test("EC-SKILL-4: a plugin upgraded mid-run does not change what an in-flight run dispatches", async () => {
  const v1Root = "/plugin/cache/pdlc/0.1.0";
  const v2Root = "/plugin/cache/pdlc/0.2.0";
  const v1File = path.join(v1Root, "skills", "pm-author", "SKILL.md");
  const v2File = path.join(v2Root, "skills", "pm-author", "SKILL.md");

  // The "upgrade": v2 appears on disk mid-run, alongside v1 (both readable) —
  // the handshake already approved v1, so nothing should ever read v2.
  const reads = [];
  const fs = {
    existsSync: (p) => p === v1File || p === v2File,
    readFileSync: (p) => {
      reads.push(p);
      if (p === v1File) return "# pm-author v1\n\nAuthor the REQ.";
      if (p === v2File) return "# pm-author v2 — UPGRADED\n\nAuthor the REQ, differently.";
      const err = new Error(`ENOENT: ${p}`);
      err.code = "ENOENT";
      throw err;
    },
  };
  const transport = { calls: [], dispatch: async function (prompt, opts) { this.calls.push({ prompt, opts }); return { text: "x" }; } };
  const adapter = createAdapter({
    transport,
    pluginRoot: v1Root, // the version the C-10 handshake approved at startup
    log: () => {},
    loadSkillFn: (root, name) => loadSkill(root, name, { fs }),
  });

  await adapter._agent("pm-author", "Write REQ, draft 1.");
  // "Upgrade" happens here, mid-run — nothing in the adapter re-resolves the root.
  await adapter._agent("pm-author", "Write REQ, draft 2.");

  assert.ok(reads.every((p) => p === v1File), `every read must stay on the handshake-approved root; saw: ${reads.join(", ")}`);
  for (const call of transport.calls) {
    assert.ok(call.prompt.includes("pm-author v1"), "every dispatch this run must carry v1 text");
    assert.equal(call.prompt.includes("UPGRADED"), false, "no dispatch this run may see the upgraded text");
  }
});
