/**
 * decisionLedgerCorpus.test.js — PLAN T-09, "[red]" (pdlc-decision-ledger).
 *
 * The corpus oracle over T-03's frozen fixture (TSPEC §3.5/§3.6, §7.6; PLAN row T-09; PROPERTIES
 * PROP-CORP family). `gatherDecisionCorpus`, `selectDecisions` and `renderDecisionLedgerBlock` do
 * not exist on `orchestrate-dev.js` at HEAD — PLAN T-17 is the sole task that lands the IO shell
 * (row T-17: "Un-skips T-08 T-09"). Every block below is therefore authored `describe.skip`,
 * titled `"T-17: …"`, and the module is loaded via a deferred dynamic `import()` inside each test
 * body — the `decisionLedgerRender.test.js` / `decisionLedgerBounds.test.js` precedent restated —
 * so this file still loads and the skips take effect while the symbols are absent.
 *
 * ## Independent-model discipline (mirrors `decisionLedgerBounds.test.js`'s PROP-BND-07)
 *
 * Every expected id, statement and byte count below is transcribed BY HAND from either (a) the
 * frozen fixture's on-disk heading text (`pdlc/workflows/__tests__/fixtures/decision-corpus/**`,
 * digest-guarded by `decisionLedgerFixtureGuard.test.js`, PLAN T-03), read with a plain editor/
 * `sed`, never generated by running any recogniser; or (b) TSPEC §3.5/§3.6's own measured table,
 * which states the same figures (45, 48, 41, 63, 6,305, 7,042, 7,650, 10,859, 12,059, 441) against
 * the identical frozen commit `8c673a09f`. `modelFormatLine` below is this file's own
 * transcription of TSPEC §4.3's stated per-record line form — never `renderDecisionLedgerBlock`,
 * never `recogniseDecisionRecords` — so a defect in the production renderer or recogniser cannot
 * silently agree with the expected side of any assertion in this file.
 *
 * AT-02 (the citation round-trip) goes one step further: it never reads a field of the
 * `DecisionRecord` the production code returns at all, on either side. It re-parses the rendered
 * line's own citation bracket with a private regex, re-opens the parsed `sourcePath` through the
 * SAME `_readFile` double `gatherDecisionCorpus` was given, and re-derives the expected statement
 * from that raw text with `MODEL_HEADING_RE` — the comparison is string-to-string throughout
 * (TSPEC §4.3, "a check reading the parsed record would compare the recogniser against itself").
 *
 * ## Bounds are supplied non-binding for AT-01 (TSPEC §7.6)
 *
 * AT-01's two dispatches (45 and 48 lines) are asserted against `DECISION_LEDGER_DEFAULTS`
 * (`maxEntries: 70`, `maxBytes: 12500`) purely as the shipped default — 45 and 48 sit far under
 * the 70-entry ceiling, and their measured byte totals (7,042 and 7,650 per TSPEC §3.6) sit far
 * under the 12,500-byte ceiling (even after the ≤1,200-byte framing charge). Neither bound fires
 * for either dispatch; AT-01 is a corpus/ordering oracle, not a bounds oracle — DEC-DECLEDGER-13's
 * two shipped-default assertions below are what exercise the bound actually binding and not.
 */

import { readFileSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";

import {
  makeGitDouble,
  makeReadFileDouble,
  makeDecisionLedgerSeams,
} from "./helpers/decisionLedgerDoubles.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FIXTURE_ROOT = path.join(__dirname, "fixtures", "decision-corpus");
const DEV_MODULE_PATH = "../orchestrate-dev.js";

// TSPEC §4.3's stated per-line form, transcribed independently here (never imported, never
// routed through the production renderer) — identical in spirit to
// `decisionLedgerBounds.test.js`'s `modelFormatLine` (PROP-BND-07), re-derived rather than
// re-exported because each test file owns its own oracle per this repo's single-writer rule.
function modelFormatLine(record) {
  return `${record.id} — ${record.statement}  [${record.sourcePath} § ${record.id}]`;
}

// TSPEC §3.2's grammar, transcribed independently for AT-02's re-parse leg only — this file's own
// model, never `DECISION_HEADING_RE`.
const MODEL_HEADING_RE =
  /^#{2,4}[ \t]+(?:\d+\.[ \t]+)?(DEC(?:-[A-Z0-9]+)+-\d+)[ \t]*[:—-][ \t]*(\S.*?)[ \t]*$/;

// The citation bracket AT-02 re-parses out of a rendered line, never out of a `DecisionRecord`
// field: "... [{sourcePath} § {id}]" at the end of the line.
const CITATION_RE = /\[(.+) § (DEC(?:-[A-Z0-9]+)+-\d+)\]$/;

// ─── the frozen fixture's 25 paths (PLAN T-03) — transcribed independently here, this file's own
// copy rather than an import from `decisionLedgerFixtureGuard.test.js`, per this repo's
// single-writer-per-file convention. ─────────────────────────────────────────────────────
const ALL_FIXTURE_PATHS = Object.freeze([
  "docs/_decisions/DECISIONS-advisory-wave-gate-questions.md",
  "docs/_decisions/DECISIONS-anchor-provenance.md",
  "docs/_decisions/DECISIONS-erratum-routing.md",
  "docs/_decisions/DECISIONS-loop-termination.md",
  "docs/_decisions/DECISIONS-model-availability.md",
  "docs/_decisions/DECISIONS-plugin-distribution.md",
  "docs/_decisions/DECISIONS-review-convergence.md",
  "docs/_decisions/DECISIONS-review-severity-bars.md",
  "docs/_decisions/DECISIONS-seam-defaults.md",
  "docs/_decisions/DECISIONS-spec-layer-boundary.md",
  "docs/_decisions/DECISIONS-test-oracle-mechanics.md",
  "docs/_decisions/DECISIONS-wave-gates.md",
  "docs/completed/pdlc-advisory-tier/DECISIONS-pdlc-advisory-tier.md",
  "docs/completed/pdlc-advisory-wave-gate/DECISIONS-pdlc-advisory-wave-gate.md",
  "docs/completed/pdlc-consolidation-agent/DECISIONS-pdlc-consolidation-agent.md",
  "docs/completed/pdlc-engine-distribution/DECISIONS-pdlc-engine-distribution.md",
  "docs/completed/pdlc-engineering-loop/DECISIONS-pdlc-engineering-loop.md",
  "docs/completed/pdlc-headless-engine/DECISIONS-headless-engine-obligations.md",
  "docs/completed/pdlc-headless-engine/DECISIONS-pdlc-headless-engine.md",
  "docs/completed/pdlc-learnings-injection/DECISIONS-pdlc-learnings-injection.md",
  "docs/completed/pdlc-loop-economics/DECISIONS-pdlc-loop-economics.md",
  "docs/completed/pdlc-plugin-retirement/DECISIONS-pdlc-plugin-retirement.md",
  "docs/completed/pdlc-wave-resume/DECISIONS-pdlc-wave-resume.md",
  "docs/discarded/pdlc-rcv-budget-stop/DECISIONS-pdlc-rcv-budget-stop.md",
  "docs/orchestrate-dev-workflow/DECISIONS-orchestrate-dev-workflow.md",
]);

const AWG_PATH = "docs/completed/pdlc-advisory-wave-gate/DECISIONS-pdlc-advisory-wave-gate.md";
const ENGLOOP_PATH = "docs/completed/pdlc-engineering-loop/DECISIONS-pdlc-engineering-loop.md";
const HE_OBLIGATIONS_PATH =
  "docs/completed/pdlc-headless-engine/DECISIONS-headless-engine-obligations.md";
const HE_ENGINE_PATH = "docs/completed/pdlc-headless-engine/DECISIONS-pdlc-headless-engine.md";

/** Reads one fixture file's raw text off disk, by its path relative to `FIXTURE_ROOT`. */
function readFixtureFile(relPath) {
  return readFileSync(path.join(FIXTURE_ROOT, relPath), "utf8");
}

/**
 * Builds `{ _git, _readFile }` seams over the WHOLE frozen fixture: `_git`'s scripted
 * `ls-files` answer lists all 25 paths (mirroring `DECISION_CORPUS_ARGV`'s live single-call
 * enumeration, TSPEC §3.1), and `_readFile` resolves each of those same 25 paths to its frozen
 * fixture content. `gatherDecisionCorpus` is what narrows this down to project-level plus one
 * feature's own directory — this helper hands it the same universe `_git` would return live.
 */
function buildFixtureSeams(paths = ALL_FIXTURE_PATHS) {
  const files = {};
  for (const relPath of paths) files[relPath] = readFixtureFile(relPath);
  const stdout = paths.join("\n");
  return makeDecisionLedgerSeams({
    _git: makeGitDouble({ "ls-files": { ok: true, stdout } }),
    _readFile: makeReadFileDouble(files),
  });
}

/** Builds the `CorpusEntry[]` shape `selectDecisions` takes directly, bypassing
 * `gatherDecisionCorpus`'s feature-directory resolution — used by the whole-fixture and
 * `M-6b`-slice DEC-DECLEDGER-13 assertions, which span more than one feature directory at once. */
function entriesFor(paths) {
  return paths.map((relPath) => ({
    path: relPath,
    text: readFixtureFile(relPath),
    readOk: true,
  }));
}

// ─── hand-transcribed corpus anchors (TSPEC §3.5's table, `M-1d`) ─────────────────────────
//
// The 41 project-level ids, transcribed by hand from `docs/_decisions/*.md`'s headings — the
// twelve `DECISIONS-plugin-retirement.md`-style namespace-less `DEC-01`…`DEC-10` questions and
// `DECISIONS-advisory-wave-gate-questions.md`'s own non-records are excluded by construction,
// never enumerated here, matching `M-4b` / `M-2e`'s "0" row.
const PROJECT_IDS = Object.freeze([
  "DEC-ANCHOR-01",
  "DEC-ERRROUTE-01",
  "DEC-ERRROUTE-02",
  "DEC-ERRROUTE-03",
  "DEC-ERRROUTE-04",
  "DEC-TERM-01",
  "DEC-TERM-02",
  "DEC-MODEL-01",
  "DEC-MODEL-02",
  "DEC-DIST-01",
  "DEC-DIST-02",
  "DEC-DIST-03",
  "DEC-DIST-04",
  "DEC-DIST-05",
  "DEC-DIST-06",
  "DEC-DIST-07",
  "DEC-CONV-01",
  "DEC-DW-01",
  "DEC-SEV-01",
  "DEC-SEV-02",
  "DEC-SEV-03",
  "DEC-ERR-01",
  "DEC-BAR-01",
  "DEC-BAR-02",
  "DEC-ERR-02",
  "DEC-ERR-03",
  "DEC-DOC-01",
  "DEC-FRZ-01",
  "DEC-ERR-04",
  "DEC-SEV-04",
  "DEC-SEAM-01",
  "DEC-LAYER-01",
  "DEC-ORACLE-01",
  "DEC-ORACLE-02",
  "DEC-ORACLE-03",
  "DEC-ORACLE-04",
  "DEC-ORACLE-05",
  "DEC-ORACLE-06",
  "DEC-WAVE-01",
  "DEC-WAVE-02",
  "DEC-WAVE-03",
]);

// `pdlc-headless-engine`'s 22 ids (`M-6b`'s floor: 14 + 8), transcribed from its two files.
const HEADLESS_ENGINE_IDS = Object.freeze([
  "DEC-HE-01",
  "DEC-HE-02",
  "DEC-HE-03",
  "DEC-HE-04",
  "DEC-HE-05",
  "DEC-HE-06",
  "DEC-HE-07",
  "DEC-HE-08",
  "DEC-ENG-01",
  "DEC-ENG-02",
  "DEC-ENG-03",
  "DEC-ENG-04",
  "DEC-ENG-05",
  "DEC-ENG-06",
  "DEC-ENG-07",
  "DEC-ENG-08",
  "DEC-ENG-09",
  "DEC-ENG-10",
  "DEC-ENG-11",
  "DEC-ENG-12",
  "DEC-ENG-13",
  "DEC-ENG-14",
]);

// `pdlc-advisory-wave-gate`'s 4 records (§3.5, `DEC-A6-01`…`04`), statement transcribed VERBATIM
// from the heading remainder on disk (`DECISIONS-pdlc-advisory-wave-gate.md` lines 261/315/362/420
// at the frozen commit) — `M-4d`'s eight non-record headings (four namespace-less `DEC-01`…`04`
// questions, four `### What follows from DEC-A6-0N` back-references) are excluded by construction.
const AWG_RECORDS = Object.freeze([
  { id: "DEC-A6-01", statement: "The pre-repair tree is captured as a dangling snapshot commit, never stashed", sourcePath: AWG_PATH },
  { id: "DEC-A6-02", statement: "An E-6 promotion is committed by its own `commitPaths` call, not by widening a task's", sourcePath: AWG_PATH },
  { id: "DEC-A6-03", statement: "The snapshot ref is wave-scoped and carries no run discriminator", sourcePath: AWG_PATH },
  { id: "DEC-A6-04", statement: "`waveBudgetPerRun: 0` is a supported affordance, validated by a new `nonNegativeInt`", sourcePath: AWG_PATH },
]);

// `pdlc-engineering-loop`'s 7 distinct ids over 13 records (§3.3, `M-3a`/`M-3c`): `DEC-LOOP-01`
// through `06` each open TWICE — a first, question opening and a second, deciding opening — and
// the statement transcribed below for each is the SECOND (deciding) opening's remainder, per
// §3.3's last-record-wins rule. `DEC-LOOP-07` opens once.
const ENGLOOP_RECORDS = Object.freeze([
  { id: "DEC-LOOP-01", statement: "Session state travels in a caller-echoed token, not a durable file", sourcePath: ENGLOOP_PATH },
  { id: "DEC-LOOP-02", statement: "The session waits; the engine process does not", sourcePath: ENGLOOP_PATH },
  { id: "DEC-LOOP-03", statement: "`corpusState` is derived from contributing blocks, and this feature owns the change", sourcePath: ENGLOOP_PATH },
  { id: "DEC-LOOP-04", statement: "`readLoopConfig` extends the provenance precedent, diverging from the five workflow-side readers only, confined to a `case` field", sourcePath: ENGLOOP_PATH },
  { id: "DEC-LOOP-05", statement: "The redactor matches published credential prefixes, not entropy", sourcePath: ENGLOOP_PATH },
  { id: "DEC-LOOP-06", statement: "`cmdQueue`'s fail-closed refusal is left untouched; the policy asymmetry lives in the loop", sourcePath: ENGLOOP_PATH },
  { id: "DEC-LOOP-07", statement: "AT-52's installed-engine leg is not landed; the hazard it targeted is covered by the packed-tree importability conjunct", sourcePath: ENGLOOP_PATH },
]);

const EXPECTED_AWG_LINES = Object.freeze(AWG_RECORDS.map(modelFormatLine));
const EXPECTED_ENGLOOP_LINES = Object.freeze(ENGLOOP_RECORDS.map(modelFormatLine));

// TSPEC §3.5/§3.6's own measured table, over the frozen commit `8c673a09f` — hand-transcribed
// literals, never recomputed from the fixture or from any renderer.
const PROJECT_ONLY_LINE_COUNT = 41;
const PLUS_AWG_LINE_COUNT = 45;
const PLUS_ENGLOOP_LINE_COUNT = 48;
const M6B_LINE_COUNT = 63; // 41 project + pdlc-headless-engine's 22
const PROJECT_ONLY_BYTES = 6305;
const M6B_BYTES = 10859;
const DEFAULT_MAX_ENTRIES = 70;
const DEFAULT_MAX_BYTES = 12500;
const FRAMING_CEILING = 1200; // §4.3's pinned framing ceiling
const M6B_MARGIN = 441; // (12500 - 1200) - 10859

describe("T-17: AT-01 — corpus oracle over T-03's frozen fixture (TSPEC §3.5/§7.6)", () => {
  test("pdlc-advisory-wave-gate dispatch renders exactly 45 lines: 41 project-level then its own 4 (bounds non-binding)", async () => {
    const { gatherDecisionCorpus, selectDecisions, DECISION_LEDGER_DEFAULTS } = await import(
      DEV_MODULE_PATH
    );
    const seams = buildFixtureSeams();
    const corpus = await gatherDecisionCorpus({ feature: "pdlc-advisory-wave-gate", ...seams });
    expect(corpus.unlistable).toBe(false);
    const result = selectDecisions({
      entries: corpus.entries,
      feature: "pdlc-advisory-wave-gate",
      thresholds: DECISION_LEDGER_DEFAULTS,
    });

    expect(result.selected).toHaveLength(PLUS_AWG_LINE_COUNT);
    expect(result.omitted).toEqual([]); // bounds explicitly non-binding for this dispatch (§7.6)

    const projectSlice = result.selected.slice(0, PROJECT_ONLY_LINE_COUNT);
    const featureSlice = result.selected.slice(PROJECT_ONLY_LINE_COUNT);
    // project-level lines first, then feature-level (§3.6's order)
    expect(projectSlice.every((r) => r.origin === "project")).toBe(true);
    expect(featureSlice.every((r) => r.origin === "feature")).toBe(true);
    expect(projectSlice.map((r) => r.id).sort()).toEqual([...PROJECT_IDS].sort());

    // M-4d's 8 non-record headings contribute no line: exactly the 4 legitimate DEC-A6-0N ids,
    // never the 8 excluded namespace-less questions / mid-heading back-references, and each
    // carries the citation's fixed sourcePath.
    expect(featureSlice.map((r) => r.id)).toEqual(AWG_RECORDS.map((r) => r.id));
    expect(featureSlice.map(modelFormatLine)).toEqual(EXPECTED_AWG_LINES);
    for (const r of featureSlice) expect(r.sourcePath).toBe(AWG_PATH);
  });

  test("pdlc-engineering-loop dispatch renders exactly 48 lines: 41 project-level then its 7 distinct ids, each carrying the second (deciding) opening", async () => {
    const { gatherDecisionCorpus, selectDecisions, DECISION_LEDGER_DEFAULTS } = await import(
      DEV_MODULE_PATH
    );
    const seams = buildFixtureSeams();
    const corpus = await gatherDecisionCorpus({ feature: "pdlc-engineering-loop", ...seams });
    expect(corpus.unlistable).toBe(false);
    const result = selectDecisions({
      entries: corpus.entries,
      feature: "pdlc-engineering-loop",
      thresholds: DECISION_LEDGER_DEFAULTS,
    });

    expect(result.selected).toHaveLength(PLUS_ENGLOOP_LINE_COUNT);
    expect(result.omitted).toEqual([]); // bounds explicitly non-binding for this dispatch (§7.6)

    const projectSlice = result.selected.slice(0, PROJECT_ONLY_LINE_COUNT);
    const featureSlice = result.selected.slice(PROJECT_ONLY_LINE_COUNT);
    expect(projectSlice.map((r) => r.id).sort()).toEqual([...PROJECT_IDS].sort());

    // 13 raw records over 7 distinct ids (`M-3a`): last-record-wins resolves each of
    // DEC-LOOP-01..06's two openings to its SECOND, deciding statement (`M-3c`); DEC-LOOP-07
    // opens once. Exactly 7 lines, never 13.
    expect(featureSlice.map((r) => r.id)).toEqual(ENGLOOP_RECORDS.map((r) => r.id));
    expect(featureSlice.map(modelFormatLine)).toEqual(EXPECTED_ENGLOOP_LINES);
    for (const r of featureSlice) expect(r.sourcePath).toBe(ENGLOOP_PATH);
  });

  test("a build that fails to scope by feature and renders all 100 feature-level ids does not satisfy either dispatch's 45/48-line expectation", async () => {
    // Negative-space control (TSPEC §3.1): the in-scope set is project-level UNION the one
    // feature directory under review, never every feature directory at once. If a defective
    // build instead unioned every feature-level id (100, per §3.5's `M-2e` sum), neither AT-01
    // dispatch above would ever observe 45 or 48 — this is why AT-01's assertions above are
    // discriminating rather than incidentally true of a broader union.
    expect(PLUS_AWG_LINE_COUNT).not.toBe(PROJECT_ONLY_LINE_COUNT + 100);
    expect(PLUS_ENGLOOP_LINE_COUNT).not.toBe(PROJECT_ONLY_LINE_COUNT + 100);
  });
});

describe("T-17: AT-02 — citation round-trip resolves back at its own source (TSPEC §4.3)", () => {
  test("every rendered line's [sourcePath § id] citation resolves, via the SAME _readFile double, to a heading whose captured statement matches the rendered statement — no DecisionRecord field read", async () => {
    const { gatherDecisionCorpus, selectDecisions, renderDecisionLedgerBlock, DECISION_LEDGER_DEFAULTS } =
      await import(DEV_MODULE_PATH);
    const seams = buildFixtureSeams();
    const corpus = await gatherDecisionCorpus({ feature: "pdlc-advisory-wave-gate", ...seams });
    expect(corpus.unlistable).toBe(false);
    const { selected } = selectDecisions({
      entries: corpus.entries,
      feature: "pdlc-advisory-wave-gate",
      thresholds: DECISION_LEDGER_DEFAULTS,
    });

    const block = renderDecisionLedgerBlock({ selected });
    // The rendered block's index lines only — never the framing — carry a citation bracket.
    const renderedLines = block
      .split("\n")
      .filter((line) => CITATION_RE.test(line));
    expect(renderedLines.length).toBe(PLUS_AWG_LINE_COUNT);

    for (const line of renderedLines) {
      // Parse sourcePath and id OUT OF THE STRING — no `.sourcePath`/`.id` field is read here.
      const citationMatch = CITATION_RE.exec(line);
      expect(citationMatch).not.toBeNull();
      const [, parsedSourcePath, parsedId] = citationMatch;

      // Parse the rendered statement out of the string too: strip the trailing citation and its
      // leading "  " separator, then the leading "{id} — " prefix.
      const withoutCitation = line.slice(0, line.length - citationMatch[0].length).replace(/ {2}$/, "");
      const idPrefix = `${parsedId} — `;
      expect(withoutCitation.startsWith(idPrefix)).toBe(true);
      const parsedStatement = withoutCitation.slice(idPrefix.length);

      // Re-open the fixture path through the SAME `_readFile` double `gatherDecisionCorpus` used.
      const reopenedText = seams._readFile(parsedSourcePath);
      expect(reopenedText).not.toBeNull();

      // Find the heading whose captured id equals the parsed id, via this file's OWN model
      // regex — never `DECISION_HEADING_RE`, never `recogniseDecisionRecords`.
      const headingLines = reopenedText.split(/\r\n|\r|\n/);
      let matchedStatement = null;
      for (const headingLine of headingLines) {
        const headingMatch = MODEL_HEADING_RE.exec(headingLine);
        if (headingMatch && headingMatch[1] === parsedId) {
          matchedStatement = headingMatch[2]; // last-wins: keep overwriting on later matches
        }
      }
      expect(matchedStatement).not.toBeNull();
      expect(matchedStatement).toBe(parsedStatement);
    }
  });
});

describe("T-17: AT-18 — cross-file precedence over a synthetic two-file corpus (TSPEC §3.4, FSPEC O-5)", () => {
  // A synthetic (never disk-fixture) two-file corpus: the SAME id recorded once in a
  // project-level file and once in a feature-level file, with DIFFERENT statements, so the two
  // origins are distinguishable in the assertion.
  const SHARED_ID = "DEC-SYNTH-01";
  const PROJECT_STATEMENT = "the project-level statement, which must be the one rendered";
  const FEATURE_STATEMENT = "the feature-level statement, which must never appear in the block";
  const SYNTH_PROJECT_PATH = "docs/_decisions/DECISIONS-synth-o5.md";
  const SYNTH_FEATURE_PATH = "docs/pdlc-synth-o5/DECISIONS-pdlc-synth-o5.md";

  function synthEntries() {
    return [
      {
        path: SYNTH_PROJECT_PATH,
        text: `## ${SHARED_ID}: ${PROJECT_STATEMENT}\n`,
        readOk: true,
      },
      {
        path: SYNTH_FEATURE_PATH,
        text: `### ${SHARED_ID}: ${FEATURE_STATEMENT}\n`,
        readOk: true,
      },
    ];
  }

  test("exactly one line carries the shared id, and its statement/sourcePath/origin are the PROJECT-level record's (positive conjunct, not cardinality alone)", async () => {
    const { selectDecisions, renderDecisionLedgerBlock, DECISION_LEDGER_DEFAULTS } = await import(
      DEV_MODULE_PATH
    );
    const result = selectDecisions({
      entries: synthEntries(),
      feature: "pdlc-synth-o5",
      thresholds: DECISION_LEDGER_DEFAULTS,
    });

    // Cardinality alone would pass under the REJECTED feature-wins rule too (TSPEC §3.4) — this
    // is why the statement/sourcePath/origin conjuncts below are asserted as well, not instead.
    const matches = result.selected.filter((r) => r.id === SHARED_ID);
    expect(matches).toHaveLength(1);
    const [record] = matches;
    expect(record.statement).toBe(PROJECT_STATEMENT);
    expect(record.sourcePath).toBe(SYNTH_PROJECT_PATH);
    expect(record.origin).toBe("project");

    const block = renderDecisionLedgerBlock({ selected: result.selected });
    expect(block).toContain(PROJECT_STATEMENT);
    // The feature-level statement is absent from the WHOLE rendered block, not merely absent
    // from the one line naming the shared id — swapping precedence direction would leave
    // cardinality green while reddening exactly this conjunct.
    expect(block).not.toContain(FEATURE_STATEMENT);
  });
});

describe("T-17: DEC-DECLEDGER-13 — shipped-default assertions at maxEntries: 70, maxBytes: 12500 (TSPEC §3.6)", () => {
  test("over the whole 141-record fixture: project-level ids survive in full, their lines total 6,305 bytes, well under maxBytes - 1,200, and omitted[] never names a project-level id", async () => {
    const { selectDecisions, DECISION_LEDGER_DEFAULTS } = await import(DEV_MODULE_PATH);
    expect(DECISION_LEDGER_DEFAULTS.maxEntries).toBe(DEFAULT_MAX_ENTRIES);
    expect(DECISION_LEDGER_DEFAULTS.maxBytes).toBe(DEFAULT_MAX_BYTES);

    const result = selectDecisions({
      entries: entriesFor(ALL_FIXTURE_PATHS),
      feature: "pdlc-decision-ledger", // no directory of this name exists in the fixture: every
      // non-project entry is still "feature" origin (§3.1's boolean partition), so this exercises
      // the deliberately over-sized 141-record whole-fixture case (§7.3) rather than any one
      // feature's own slice.
      thresholds: DECISION_LEDGER_DEFAULTS,
    });

    const projectSelected = result.selected.filter((r) => r.origin === "project");
    expect(projectSelected.map((r) => r.id).sort()).toEqual([...PROJECT_IDS].sort());

    const projectLinesBytes = Buffer.byteLength(projectSelected.map(modelFormatLine).join("\n"), "utf8");
    expect(projectLinesBytes).toBe(PROJECT_ONLY_BYTES);
    expect(PROJECT_ONLY_BYTES).toBeLessThanOrEqual(DEFAULT_MAX_BYTES - FRAMING_CEILING);

    // 141 records over maxEntries: 70 forces omission; project-level, ordered first, is never
    // the leg omitted from (§3.6's "loop drops from the back", never the front).
    expect(result.omitted.length).toBeGreaterThan(0);
    const omittedIds = new Set(result.omitted.map((o) => o.id));
    for (const id of PROJECT_IDS) expect(omittedIds.has(id)).toBe(false);
  });

  test("over the M-6b slice (41 project-level + pdlc-headless-engine's 22 = 63): nothing is omitted, all 63 ids render, and the index lines total 10,859 bytes — 441 bytes under the 11,300-byte line budget", async () => {
    const { selectDecisions, DECISION_LEDGER_DEFAULTS } = await import(DEV_MODULE_PATH);

    const projectPaths = ALL_FIXTURE_PATHS.filter((p) => p.startsWith("docs/_decisions/"));
    const m6bPaths = [...projectPaths, HE_OBLIGATIONS_PATH, HE_ENGINE_PATH];

    const result = selectDecisions({
      entries: entriesFor(m6bPaths),
      feature: "pdlc-headless-engine",
      thresholds: DECISION_LEDGER_DEFAULTS,
    });

    expect(result.omitted).toEqual([]);
    expect(result.selected).toHaveLength(M6B_LINE_COUNT);
    const expectedIds = [...PROJECT_IDS, ...HEADLESS_ENGINE_IDS].sort();
    expect(result.selected.map((r) => r.id).sort()).toEqual(expectedIds);

    const indexBytes = Buffer.byteLength(result.selected.map(modelFormatLine).join("\n"), "utf8");
    expect(indexBytes).toBe(M6B_BYTES);
    const lineBudget = DEFAULT_MAX_BYTES - FRAMING_CEILING; // 11,300
    expect(indexBytes).toBeLessThanOrEqual(lineBudget);
    expect(lineBudget - indexBytes).toBe(M6B_MARGIN);

    // DEC-DECLEDGER-16: the 12,059-byte (index + framing) block total is deliberately NOT
    // asserted as an equality here — only the index-lines figure (10,859) and the line-budget
    // inequality above are pinned.
  });
});
